// import Head from "next/head";
// import { FaExternalLinkAlt } from "react-icons/fa";
// import Layout from "@components/Layout";
// import Container from "@components/Container";
// import Button from "@components/Button";

// import styles from "@styles/Page.module.scss";
// import { getApolloClient } from "@lib/aplloClient";
// import { gql } from "@apollo/client";
// import Map from "@components/Map";
// import center from "@turf/center";
// import { points } from "@turf/helpers";
// import { useEffect, useState } from "react";

// export default function Stores({ stores }) {
//   const [activeStore, setActiveStore] = useState();

//   const features = points(
//     stores.map((store) => {
//       return [store.location.latitude, store.location.longitude];
//     })
//   );

//   const [defaultLatitude, defaultLongitude] =
//     center(features)?.geometry.coordinates;

//   return (
//     <Layout>
//       <Head>
//         <title>{stores.name}</title>
//         <meta name="description" content="Generated by create next app" />
//       </Head>

//       <Container>
//         <h1>Stores Locations</h1>

//         <div className={styles.stores}>
//           <div className={styles.storesLocations}>
//             <ul className={styles.locations}>
//               {stores.map((store) => {
//                 return (
//                   <li key={store.id}>
//                     <p className={styles.locationName}>{store.name}</p>
//                     <address>{store.address}</address>
//                     <p>{store.phoneNo}</p>
//                     <p className={styles.locationDiscovery}>
//                       <Button onClick={() => setActiveStore(store.id)}>
//                         View on Map
//                       </Button>
//                       <a
//                         href={`http://maps.google.com/maps?z=12&t=m&q=loc:${store.location.latitude}+${store.location.longitude}`}
//                         target="_blank"
//                         rel="noreferrer"
//                       >
//                         Get Directions
//                         <FaExternalLinkAlt />
//                       </a>
//                     </p>
//                   </li>
//                 );
//               })}
//             </ul>
//           </div>

//           {/* Google Map  */}
//           <div className={styles.storesMap}>
//             <div className={styles.storesMapContainer}>
//               <Map
//                 className={styles.map}
//                 center={[defaultLatitude, defaultLongitude]}
//                 zoom={12}
//                 scrollWheelZoom={true}
//               >
//                 {({ TileLayer, Marker, Popup }, map) => {
//                   const MapEffect = () => {
//                     useEffect(() => {
//                       if (!activeStore) return;
//                       const { location } = stores.find(
//                         ({ id }) => id === activeStore
//                       );
//                       map.setView([location.latitude, location.longitude], 14);
//                     }, [activeStore]);
//                     return null;
//                   };
//                   return (
//                     <>
//                       <MapEffect />
//                       <TileLayer
//                         attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
//                         url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
//                       />
//                       {stores.map((store) => {
//                         const { latitude, longitude } = store.location;
//                         return (
//                           <Marker
//                             key={store.id}
//                             position={[latitude, longitude]}
//                           >
//                             <Popup>
//                               <p>{store.name}</p>
//                               <p>{store.address}</p>
//                             </Popup>
//                           </Marker>
//                         );
//                       })}
//                     </>
//                   );
//                 }}
//               </Map>
//             </div>
//           </div>
//         </div>
//       </Container>
//     </Layout>
//   );
// }

// export async function getStaticProps() {
//   const client = getApolloClient();

//   const data = await client.query({
//     query: gql`
//       query StoreLocations {
//         store_Locations {
//           id
//           name
//           phoneNo
//           address
//           location {
//             distance(from: { latitude: 1.5, longitude: 1.5 })
//             latitude
//             longitude
//           }
//         }
//       }
//     `,
//   });
//   const stores = data.data.store_Locations;

//   return {
//     props: {
//       stores,
//     },
//   };
// }
