// import { gql } from "@apollo/client";
// import Button from "@components/Button";
// import Container from "@components/Container";
// import Layout from "@components/Layout";
// import { getApolloClient } from "@lib/aplloClient";
// import Head from "next/head";
// import React from "react";
// import styles from "@styles/Page.module.scss";
// import Link from "next/link";

// const Categories = ({ Categories, taha }) => {
//   return (
//     <Layout>
//       <Head>
//         <title>Categories</title>
//         <meta name="description" content="Generated by create next app" />
//       </Head>
//       <Container>
//         {Categories.map((categories) => {
//           return (
//             <div key={categories.id}>
//               <h1>{categories.name}</h1>
//               <Button>Add Me</Button>
//             </div>
//           );
//         })}
//       </Container>
//     </Layout>
//   );
// };

// export default Categories;

// export async function getStaticProps() {
//   const client = getApolloClient();
//   const data = await client.query({
//     query: gql`
//       query CategoriesPage {
//         categories {
//           id
//           name
//           slug
//           products {
//             id
//             image
//             name
//             price
//             slug
//           }
//         }
//       }
//     `,
//   });

//   //   const Categories = data.data.categories.map((categories) => {
//   //     const Products = categories.products;
//   //     return Products;
//   //   });

//   const Categories = data.data.categories;
//   //   const taha = Categories.Category.map((category) => {
//   //     return {
//   //       params: {
//   //         categoryProducts: category.products,
//   //       },
//   //     };
//   //   });

//   return {
//     props: {
//       Categories,
//       // taha,
//     },
//   };
// }
